name: LAGraph CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - {a: a12, b: b34}
        - {a: a56, b: b78}
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      run: |
        echo ${{ matrix.config.a }}
        echo ${{ matrix.config.b }}
