name: LAGraph CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [{a: 'a12', b: 'b34'}, {a: 'c56', b: '78'}]
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      run: |
        echo {{ matrix.node }}
        echo {{ matrix.node['a'] }}
        echo {{ matrix.node['b'] }}
