name: LAGraph CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      run: |
        pushd .
        # grab GraphBLAS binaries
        mkdir graphblas-binaries
        cd graphblas-binaries
        wget --quiet https://anaconda.org/conda-forge/graphblas/4.0.3/download/linux-64/graphblas-4.0.3-h9c3ff4c_0.tar.bz2
        tar xf graphblas-4.0.3-h9c3ff4c_0.tar.bz2
        export GRAPHBLAS_INCLUDE_DIR=`pwd`/include
        export GRAPHBLAS_LIBRARY=`pwd`/lib/libgraphblas.so
        popd
        # build and test LAGraph
        mkdir build
        cd build
        CC=gcc cmake .. -DGRAPHBLAS_INCLUDE_DIR=${GRAPHBLAS_INCLUDE_DIR} -DGRAPHBLAS_LIBRARY=${GRAPHBLAS_LIBRARY}
        JOBS=2 make
  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      run: |
        pushd .
        # grab GraphBLAS binaries
        mkdir graphblas-binaries
        cd graphblas-binaries
        wget --quiet https://anaconda.org/conda-forge/graphblas/4.0.3/download/osx-64/graphblas-4.0.3-h046ec9c_0.tar.bz2
        tar xf graphblas-4.0.3-h046ec9c_0.tar.bz2
        export GRAPHBLAS_INCLUDE_DIR=`pwd`/include
        export GRAPHBLAS_LIBRARY=`pwd`/lib/libgraphblas.dylib
        popd
        # build and test LAGraph
        mkdir build
        cd build
        CC=gcc cmake .. -DGRAPHBLAS_INCLUDE_DIR=${GRAPHBLAS_INCLUDE_DIR} -DGRAPHBLAS_LIBRARY=${GRAPHBLAS_LIBRARY}
        JOBS=2 make
